[global]
type = global
user_agent = Provaani-Asterisk-SBC

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060
external_media_address = 34.131.238.156
external_signaling_address = 34.131.238.156
local_net = 172.16.0.0/12
local_net = 10.0.0.0/8
local_net = 192.168.0.0/16

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060
external_media_address = 34.131.238.156
external_signaling_address = 34.131.238.156
local_net = 172.16.0.0/12
local_net = 10.0.0.0/8
local_net = 192.168.0.0/16

; Inbound Endpoint from Plivo Zentrunk
[plivo_inbound]
type = endpoint
context = from-plivo
disallow = all
allow = ulaw,alaw,g722
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
inband_progress = yes
dtmf_mode = rfc4733

[plivo_identify]
type = identify
endpoint = plivo_inbound
match = 0.0.0.0/0
