map $uri $media_content_type {
    ~\.wav$            audio/wav;
    ~\.mp3$            audio/mpeg;
    ~\.txt$            "text/plain; charset=utf-8";
    default            application/octet-stream;
}

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
    }

    location /voice-audio/ {
        proxy_pass http://minio:9000;
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
        proxy_hide_header Content-Type;
        add_header Content-Type $media_content_type always;
    }

    location /analysis/ {
        proxy_pass http://analysis-service:8001/analyze/;
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }
}
